CREATE DATABASE coffee_shop;
USE coffee_shop;

-- Creating table
-- City

CREATE TABLE city
(
   city_id INT PRIMARY KEY,
   city_name VARCHAR(20),
   population BIGINT,
   estimated_rent FLOAT,
   city_rank int
);   

select * from city;

-- Products Table
CREATE TABLE products
(
	product_id	INT PRIMARY KEY,
	product_name VARCHAR(35),	
	Price float
);

-- Customers Table
CREATE TABLE customers
(
	customer_id INT PRIMARY KEY,	
	customer_name VARCHAR(25),	
	city_id INT,
	CONSTRAINT fk_city FOREIGN KEY (city_id) REFERENCES city(city_id)
);

-- Sales Table
CREATE TABLE sales
(
	sale_id	INT PRIMARY KEY,
	sale_date	date,
	product_id	INT,
	customer_id	INT,
	total FLOAT,
	rating INT,
	CONSTRAINT fk_products FOREIGN KEY (product_id) REFERENCES products(product_id),
	CONSTRAINT fk_customers FOREIGN KEY (customer_id) REFERENCES customers(customer_id) 
);

-- Checking all the tables
SELECT * FROM city;
SELECT * FROM products;
SELECT * FROM customers;
SELECT * FROM sales;

----------------------------------------------------------------------------------------------
-- Importing the datasets
-- by using Table Data Import Wizard

-- city
SELECT * FROM city;

-- customers
SELECT * FROM customers;

-- products
SELECT * FROM products;

-- sales
SELECT * FROM sales;

DESCRIBE sales;
SELECT COUNT(*) FROM sales;
TRUNCATE TABLE sales;

SELECT VERSION();

-- Checking all the tables
SELECT * FROM city;
SELECT * FROM products;
SELECT * FROM customers;
SELECT * FROM sales;
-------------------------------------------------------------------------------------------------------------------------------
-- Coffee Shop Business Expansion Analysis
-------------------------------------------------------------------------------------------------------------------------------
-- Business Insights Problems 
-------------------------------------------------------------------------------------------------------------------------------

-- 1. What is the total revenue generated by the coffee shop?
USE coffee_shop;
SELECT
    SUM(total) AS total_revenue
FROM sales;

-- 🔍 Business Problem
-- The company does not know how much revenue has been generated from all coffee sales.
-- Without knowing total revenue, management cannot evaluate overall business performance.

-- 💡 Business Impact
-- Measures overall business performance
-- Helps track business growth
-- Acts as a baseline for future analysis
---------------------------------------------------------------------------------------------------------------------------------------

-- 2. How many customers are registered in the coffee shop?

SELECT COUNT(customer_id) AS Total_customers
FROM customers;

-- 🔍 Business Problem
-- The company does not know the size of its customer base.
-- Without knowing the number of customers, it is difficult to measure business reach and growth.

-- 💡 Business Impact
-- Measures total customer reach
-- Helps evaluate business growth
-- Useful for marketing and customer retention planning
----------------------------------------------------------------------------------------------------------------------------------------

-- 3. How much revenue was generated from each city?

SELECT city.city_name,
       SUM(sales.total) AS total_revenue
FROM sales
JOIN customers
ON sales.customer_id = customers.customer_id
JOIN city
ON customers.city_id = city.city_id
GROUP BY city.city_name
ORDER BY total_revenue DESC;

-- 🔍 Business Problem
-- The company knows total revenue but does not know which cities are contributing the most revenue.
-- Without city-wise revenue analysis, management cannot identify high-performing markets.

-- 💡 Business Impact
-- Identifies top-performing cities
-- Helps prioritize expansion opportunities
-- Supports city-level marketing decisions
-- Reveals which locations generate the most revenue
---------------------------------------------------------------------------------------------------------------------------------------

-- 4. How many customers belong to each city?

SELECT city_name,
       COUNT(customer_id) AS total_customers
FROM customers
JOIN city
ON customers.city_id = city.city_id
GROUP BY city_name
ORDER BY total_customers DESC;

-- 🔍 Business Problem
-- The company knows its total number of customers, but it does not know which cities have the highest concentration of customers.
-- Without this information, management cannot identify strong customer markets.

-- 💡 Business Impact
-- Identifies cities with the largest customer base
-- Helps target marketing campaigns
-- Supports future store expansion decisions
-- Helps understand customer distribution
---------------------------------------------------------------------------------------------------------------------------------------

-- 5.Which products were sold the most?

SELECT product_name,
       COUNT(*) AS total_sales
FROM sales
JOIN products
ON sales.product_id = products.product_id
GROUP BY product_name
ORDER BY total_sales DESC;

-- 🔍 Business Problem
-- The company does not know which products customers purchase most frequently.
-- Without this information, inventory planning and product strategy become difficult.

-- 💡 Business Impact
-- Identifies customer favorite products
-- Helps maintain sufficient stock of popular items
-- Prevents inventory shortages
-- Supports promotional and pricing decisions
-----------------------------------------------------------------------------------------------------------------------------------------

-- 6. How much revenue did each product generate?

SELECT product_name,
       SUM(total) AS total_revenue
FROM sales
JOIN products
ON sales.product_id = products.product_id
GROUP BY product_name
ORDER BY total_revenue DESC;

-- 🔍 Business Problem
-- The company knows which products are sold frequently, but it does not know which products generate the most revenue.
-- A product may sell many times but still generate less revenue than a higher-priced product.

-- 💡 Business Impact
-- Identifies the most profitable products
-- Helps prioritize high-revenue items
-- Supports pricing and promotion strategies
-- Helps improve product portfolio decisions

---------------------------------------------------------------------------------------------------------------------------------------

-- 7. What is the average sale amount of all transactions?SELECT AVG(total) AS average_sale_amount

SELECT ROUND(AVG(total)) AS average_sale_amount
FROM sales;

-- 🔍 Business Problem
-- The company knows total revenue, but it does not know the average value of a customer transaction.
-- Without this information, management cannot understand typical customer spending behavior.

-- 💡 Business Impact
-- Measures average customer spending per transaction
-- Helps evaluate pricing strategy
-- Useful for revenue forecasting
-- Can be used to track business performance over time
-------------------------------------------------------------------------------------------------------------------------------------------

-- 8. Which customers spent the most money?

SELECT customer_name,
       SUM(total) AS total_spent
FROM sales
JOIN customers
ON sales.customer_id = customers.customer_id
GROUP BY customer_name
ORDER BY total_spent DESC;

-- 🔍 Business Problem
-- The company has many customers, but it does not know which customers contribute the most revenue.
-- Without identifying high-value customers, the company may miss opportunities for loyalty programs and targeted promotions.

-- 💡 Business Impact
-- Identifies the most valuable customers
-- Helps create loyalty and reward programs
-- Supports targeted marketing campaigns
-- Improves customer retention
--------------------------------------------------------------------------------------------------------------------------------------

-- 9. What is the average spending per customer in each city?

SELECT city_name,
       ROUND(AVG(total)) AS average_spending
FROM sales
JOIN customers
ON sales.customer_id = customers.customer_id
JOIN city
ON customers.city_id = city.city_id
GROUP BY city_name
ORDER BY average_spending DESC;

-- 🔍 Business Problem
-- The company knows total revenue and total customers, but it does not know how much customers spend on average in different cities.
-- Without this information, management cannot identify high-value markets.

-- 💡 Business Impact
-- Identifies cities where customers spend more money
-- Helps prioritize premium markets
-- Supports city-level marketing decisions
-- Helps choose better locations for future expansion
-----------------------------------------------------------------------------------------------------------------------------------------

-- 10. Show city name, total customers, total revenue, and population to identify the best city for opening a new outlet.

SELECT city.city_name,
       city.population,
       COUNT(DISTINCT customers.customer_id) AS total_customers,
       SUM(sales.total) AS total_revenue
FROM sales
JOIN customers
ON sales.customer_id = customers.customer_id
JOIN city
ON customers.city_id = city.city_id
GROUP BY city.city_name, city.population
ORDER BY total_revenue DESC;

-- 🔍 Business Problem
-- The company wants to open new coffee outlets but does not know which cities offer the best business opportunity.
-- Choosing a city without data could lead to poor investment decisions.

-- 💡 Business Impact
-- Supports data-driven expansion
-- Reduces business risk
-- Identifies high-potential markets
-- Maximizes return on investment

-------------------------------------------------------------------------------------------------------------------------------------------

# Final Recommendation

-- After analyzing revenue, customer distribution, product performance, and customer spending patterns across different cities,
-- the following cities are recommended for future coffee shop expansion.

## 🥇 City 1: Pune

### Why Pune?

-- ✅ Highest revenue generation
-- ✅ Strong average customer spending
-- ✅ Large and active customer base
-- ✅ High demand for coffee products

### Recommendation
-- Pune should be the first choice for expansion because it demonstrates strong revenue performance 
-- and healthy customer spending behavior, making it a highly profitable market.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## 🥈 City 2: Chennai

### Why Chennai?
-- ✅ Second-highest revenue contribution
-- ✅ Consistent customer demand
-- ✅ Strong customer base
-- ✅ Good balance between revenue and market opportunity

### Recommendation
-- Chennai offers a balanced combination of revenue and customer activity, making it an attractive location for the second outlet.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

## 🥉 City 3: Jaipur

### Why Jaipur?

-- ✅ High customer count
-- ✅ Growing coffee consumer base
-- ✅ Strong revenue relative to market size
-- ✅ Expansion potential for future growth

### Recommendation
-- Jaipur represents an emerging market with significant growth potential and should be considered for the third outlet.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Cities Not Recommended

### Bangalore

-- ❌ Revenue performance does not justify operational costs
-- ❌ Higher cost of doing business
-- ❌ Greater profitability risk compared to top-ranked cities
-- **Conclusion:** Expansion in Bangalore should be postponed until stronger revenue growth is observed.

----

### Delhi

-- ❌ Customer spending is lower compared to leading cities
-- ❌ Revenue efficiency is relatively weaker
-- ❌ Better opportunities exist in other cities
-- **Conclusion:** Delhi has market potential, but current business metrics suggest that other cities offer a better return on investment.

--------------------------------------------------------------------------------------------------------------------------------------------------------------

# Overall Conclusion
-- Based on the SQL analysis, Pune, Chennai, and Jaipur provide the strongest combination of revenue generation, customer demand, and growth potential.
-- Expanding into these cities is expected to maximize business growth while minimizing expansion risk.
